### ISSUE TITLE
location does not seem to work

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/vgrid#11]
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/6021844/175845611-814ddb4f-dd0e-4cb5-9e2c-cf0b23253fbf.png">

I am sure there are nodes in lochristi

- how can I know anyhow which locations there are, this feature is not very usable
    - maybe there should be a query where we can get all cities and all countries
- we need to make sure search is case insensitive (on server)

lets make this usable

**Comment by despiegk** [comment]
see aso #2

**Comment by despiegk** [comment]
coordinate with rest proxy server team, needs to be fixed there too

**Comment by sameh-farouk** [comment]
I think the nodes in `Lochristi` is in qa network now, not on testnet.

**Comment by sameh-farouk** [comment]
> coordinate with rest proxy server team, needs to be fixed there too

okay, any feedback? @xmonader @AhmedHanafy725 @OmarElawady

**Comment by sameh-farouk** [comment]
I opened an issue to be dealt with string case from the server-side. also, I have changed the example script get_nodes_by_city_country.v to modify the search query and convert it to the right case no matter what case is used.

![Screenshot from 2022-06-29 22-21-54](https://user-images.githubusercontent.com/42457449/176537831-fb3b5f6f-6021-4e46-8cba-5d8be5f381b8.png)

**Comment by despiegk** [comment]
still leaves the main issue which is, how can I know which countries/cities there are?

**Comment by sameh-farouk** [comment]
I opened this issue to be dealt with from the server side:

https://github.com/threefoldtech/tfgridclient_proxy/issues/176

Without API support, From the client side there is no thing can be done to query these info (efficiently). Any suggestions?

**Comment by xmonader** [comment]
> still leaves the main issue which is, how can I know which countries/cities there are?

can use the stats endpoint https://gridproxy.dev.grid.tf/stats it gives you the nodes distribution

**Comment by sameh-farouk** [comment]
the suggested solution would work just fine.
you can find in the client usage how to query the stat endpoint using the vgrid client

**Usage:**
https://github.com/threefoldtech/vgrid/blob/development/gridproxy/README.md#client-usage

**More info:**
- GridStat Model:
https://github.com/threefoldtech/vgrid/blob/development/gridproxy/docs/threefoldtech.vgrid.gridproxy.model.md#gridstat
- get_stat method:
https://github.com/threefoldtech/vgrid/blob/development/gridproxy/docs/threefoldtech.vgrid.gridproxy.md#get_stats
