### ISSUE TITLE
examples not working for me

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/vgrid#12]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/6021844/178089478-2afe6be5-98f5-432e-99b8-416791bf558d.png">

**Comment by sameh-farouk** [comment]
please run the code (execute v run) from outside the module directory, in this case, the `vgrid` directory.

I opened [an issue](https://github.com/vlang/v/issues/14859) one month ago in the v lang repo, about this import unexpected behaviour, they mark the issue as a bug 6 days ago but not fixed yet.
