### ISSUE TITLE
implement vgrid proxy in vlang client

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/vgrid#5]
client for https://gridproxy.test.grid.tf/swagger/index.html 
because the explorer is not there any more

do the basics first, get request make the vlang structs fill them in...

**Comment by sameh-farouk** [comment]
**Update:**
Just pushed the [initial implementation of the gridproxy client](https://github.com/threefoldtech/vgrid/pull/6). it now implements functions to interact with all [grid proxy API endpoints](https://gridproxy.qa.grid.tf/swagger/index.html#/).

Some models have helper methods, which should be useful for converting the units returned from the API to more human readale formats/units. (time units/ storage units/ TFT units)
I also wrote tests to cover the main functionality of the client.

Tomorrow will write some docs. and later we can add more high-level functions to enhance the user experience.

This is a WIP, so probably will need to clean and refactor some parts later after getting some feedback and giving it a test.

![Screenshot from 2022-06-22 19-47-27](https://user-images.githubusercontent.com/42457449/175103254-b7620b50-7c35-4e92-8d10-aaee3c0ad546.png)

**Comment by sameh-farouk** [comment]
Docs and initial pipeline have been added too

PR is ready for review:
https://github.com/threefoldtech/vgrid/pull/6

**Comment by rkhamis** [comment]
@despiegk please review. I'm moving this to 3.7

**Comment by xmonader** [comment]
> @despiegk please review. I'm moving this to 3.7

I merged, all the points seems to be checked. Please reopen if you have further comments @despiegk
