### ISSUE TITLE
cant use library, maybe wrong crystallib?

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/vgrid#7]
v run /Users/despiegk1/.vmodules/threefoldtech/vgrid/examples/get_nodes_by_capacity.v

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/6021844/175771108-c5201433-c935-4769-8922-6e975bb0489c.png">

did you upgrade your crystallib
also crystallib is since a while on a different path

**Comment by despiegk** [comment]
please use 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/6021844/175771190-c46f3c7f-ecc9-41a2-a631-f3e4fb0ca2fc.png">

**Comment by sameh-farouk** [comment]
The client code uses the correct path for importing crystallib, however, it relays on the httpconnection module which has an outdated import path. So In the CI, I tried to have a copy in the old path too, to maintain compatibility but this is only a temp fix.

This what I opened this issue a few days ago and was waiting for your feedback.

https://github.com/freeflowuniverse/crystallib/issues/75

We should scan the old code base, all scripts, modules, etc, and make sure it has the new path for crystallib. I can do so if you agree.

Regarding the ‘examples’, and ‘explorer’ directories you tried to run code from, they are obsolete now, and should be removed. All functional code exists in the gridproxy dir. 
Have a look at the new client docs here.

https://github.com/threefoldtech/vgrid/blob/development-gridproxy_client/gridproxy/README.md

And hee too

https://github.com/threefoldtech/vgrid/blob/development-gridproxy_client/gridproxy/docs/gridproxy.md

https://github.com/threefoldtech/vgrid/blob/development-gridproxy_client/gridproxy/docs/gridproxy.model.md

If you need any further explanation please let me know.
