### ISSUE TITLE
use better units

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/vgrid#9]
```
    updated_at:     threefoldtech.vgrid.gridproxy.model.UnixTime(1656293292)
    capacity: threefoldtech.vgrid.gridproxy.model.NodeCapacity{
        total_resources: threefoldtech.vgrid.gridproxy.model.NodeResources{
            cru: 24
            mru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(202802905088)
            sru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(512110190592)
            hru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(9001778946048)
        }
        used_resources: threefoldtech.vgrid.gridproxy.model.NodeResources{
            cru: 8
            mru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(32091450573)
            sru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(218468712448)
            hru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(0)
        }
```

no-one can reason with bytes, please just change to int32 representing MByte

change the names to mru_mb

is easier to read, for sizes we can use mbyte everywhere, and easier to reason with

### secondunit

I believe following is too confusing and more complex than it should
threefoldtech.vgrid.gridproxy.model.SecondUnit(4699431)

just make it an int and represent days, anything less than a day people dont dare
change field to uptime_days

### status

please document somewhere what statuses there are, can we make this enumerator?

###  public_config: threefoldtech.vgrid.gridproxy.model.PublicConfig{

what does this mean>
- gw4 is string?
- ipv4 same?
- ...

**Comment by despiegk** [comment]
certification can be enumerator too

**Comment by sameh-farouk** [comment]
> ```
>     updated_at:     threefoldtech.vgrid.gridproxy.model.UnixTime(1656293292)
>     capacity: threefoldtech.vgrid.gridproxy.model.NodeCapacity{
>         total_resources: threefoldtech.vgrid.gridproxy.model.NodeResources{
>             cru: 24
>             mru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(202802905088)
>             sru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(512110190592)
>             hru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(9001778946048)
>         }
>         used_resources: threefoldtech.vgrid.gridproxy.model.NodeResources{
>             cru: 8
>             mru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(32091450573)
>             sru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(218468712448)
>             hru:             threefoldtech.vgrid.gridproxy.model.ByteUnit(0)
>         }
> ```
> 
> no-one can reason with bytes, please just change to int32 representing MByte
> 
> change the names to mru_mb
> 
> is easier to read, for sizes we can use mbyte everywhere, and easier to reason with
> 

I already implemented and documented helper methods.
so you can just access any ByteUnit (like `mru`, `hru` and `sru`) filed and invoke its methods directly

```v
node.capacity.total_resources.mru // mru in original API call unit (bytes)
node.capacity.total_resources.mru.to_megabytes() // mru in MB
node.capacity.total_resources.mru.to_gigabytes() // mru in GB
node.capacity.total_resources.mru.to_terabytes() // mru in TB
```

**Comment by sameh-farouk** [comment]
> ### secondunit
> I believe following is too confusing and more complex than it should threefoldtech.vgrid.gridproxy.model.SecondUnit(4699431)
> 
> just make it an int and represent days, anything less than a day people dont dare change field to uptime_days

I agree here too, this is why I implemented and documented some helper methods that you can just invoke it on any SecondUnit field (like `uptime`)

```v
node.uptime // // uptime in original API call unit (seconds)
node.uptime.to_hours() // uptime in hours
node.uptime.to_days() // uptime in days
```

**Comment by sameh-farouk** [comment]
> ### status
> please document somewhere what statuses there are, can we make this enumerator?

okay will do

**Comment by sameh-farouk** [comment]
> ### public_config: threefoldtech.vgrid.gridproxy.model.PublicConfig{
> what does this mean>
> 
> * gw4 is string?
> * ipv4 same?

they are not well documented either in the API doc or swagger doc. but will add a better descriptions to these in the client docs.

**Comment by sameh-farouk** [comment]
extra note regarding client units besides what I mentioned in previous comments,  i can provide a better str() method  so we get output like `15 days, 4 hours, 35 minutes, and 15 seconds`

```v
pub fn (u SecondUnit) str() string {
    days := // some math
    hours := // some math 
    minutes := // some math 
    seconds := // some math 
    return '{$days days, $hours hours, ${minutes} minutes, and ${seconds} seconds}'
}

**Comment by sameh-farouk** [comment]
**Update:**
I have [implemented](https://github.com/threefoldtech/vgrid/commit/ca6e4a0594465d7213887363d18690d6e9da1554) a smart cast in all unit types, it will guarantee to **display** the supported field's value with the most reasonable unit based on how big or small the value is. please check now. all example scripts were updated as well as the docs with more optional args (--network, --cache, and --max-count)

![Screenshot from 2022-06-28 14-46-16](https://user-images.githubusercontent.com/42457449/176182571-1871866d-0e59-4117-9b31-6480876413b6.png)
